---
title: "01_Bar_Chart"
author: "Calla Bush St George"
date: "`r Sys.Date()`"
output:
  html_document: 
    code_folding: show
    theme: spacelab
    highlight: pygments
    keep_md: no
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
      toc_depth: 3
  keep_md: true  
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      fig.align = "center",
                      fig.path = "../figures/09_ASV_percentage/")
```

# Goals

1. Make bar chart to find ASV cutoff point

## Load Libraries
```{r load-packages}
# Install packages if needed
pacman::p_load(tidyverse, devtools, phyloseq, patchwork, vegan, ggpubr, rstatix,
               ggplot2, readxl, install = FALSE)
```

```{r load-colors}
host_species_colors <- c(
  "Acanthurus nigros" = "dodgerblue4",
  "Acanthurus achilles" = "blue",
  "Acanthurus nigrofuscus" = "darkblue",
  "Acanthurus olivaceus" = "steelblue2",
  "Acanthurus triostegus" = "slateblue",
  "Ctenochaetus striatus" = "deeppink",
  "Naso brevirostris" = "brown",
  "Naso lituratus" = "brown2",
  "Naso tonganus" = "coral1",
  "Naso unicornis" = "red",
  "Odax pullus" = "green",
  "Zebrasoma flavescens" = "gold",
  "Zebrasoma scopas" = "gold4",
  "Zebrasoma velifer" = "burlywood")
```

## Load in data 
```{r load-excel}
# Load in ASV counts from no threes
#ASV_counts_epulos <- 
#  read_excel("no_threes/data/01_DADA2/04_end_files/ASV_counts_copy.xlsx")

ASV_counts_copy <- read_excel("~/Desktop/ASV_counts_copy.xlsx")

#View(ASV_counts_copy)
```

## Prep bar chart
```{r prep-bar-chart}

# Sort
ASV_counts_copy <- ASV_counts_copy[order(ASV_counts_copy$Counts),]

# plot data
ggplot(data = ASV_counts_copy, aes(x = reorder(ASVs, Counts), y = Counts)) + 
  geom_bar(stat = "identity") + theme_bw()

```

# Quartiles
```{r calculate quartiles}
res<-quantile(ASV_counts_copy$Counts, probs = c(0,0.25,0.5,0.75,1))
res
1 + 2 + 3 + 21
```



